### ISSUE TITLE
Fatal error: Call to a member function getAyatNumber() on a non-object in C:\xampp\htdocs\laraiba\show_translation.php

### ISSUE THREAD

**Issue by rkukuh** [laraiba/php-quran-resource#3]
Halo gan.. ada isu dari kode Show Translation yang di code sample..

Ini skrinsyut'nya gan:

![laraiba](https://cloud.githubusercontent.com/assets/183228/5424483/4ebc45a0-8323-11e4-9cf7-89c771d39458.png)

**Comment by andylibrian** [comment]
Sudah diperbaiki, silakan diupdate menggunakan composer.

```
$ php composer.phar update
```

Thanks @rkukuh
